TST YIACO HR/Employee Appraisal/Controllers/AppraisalReportsController.cs
using Employee_Appraisal.AIFEmployee;
using Employee_Appraisal.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Employee_Appraisal.Controllers
{
    public class AppraisalReportsController : Controller
    {
        private YIACOAPPSDBEntities db = new YIACOAPPSDBEntities();
        List<EmpReport> Query;
        List<EmpListReport> employeeList = new List<EmpListReport>();
        AxdEntity_EmplTable_1 employee;

        public class EmpReport
        {
            public int AppraisalId { get; set; }
            public string EmplId { get; set; }
            public string EmplName { get; set; }
            public string EmplOrganization { get; set; }
            public string EmplPosition { get; set; }
            public double ADMN { get; set; }
            public double COM { get; set; }
            public double SALES { get; set; }
            public double RESP { get; set; }
            public double TOTAL { get; set; }
        }

        public class DevReport
        {
            public int AppraisalId { get; set; }
            public string EmplId { get; set; }
            public string EmplName { get; set; }
            public string EmplOrganization { get; set; }
            public string EmplPosition { get; set; }
            public string DevelopmentNeeds { get; set; }
            public string DevelopmentNeedsText { get; set; }
            public string TargetDate { get; set; }
            public string ActionPlan { get; set; }
        }

        public class EmpListReport
        {
            public string EmplId { get; set; }
            public string EmplName { get; set; }
            public string EmplOrganization { get; set; }
            public string EmplPosition { get; set; }
            public DateTime JoinDate { get; set; }
            public string ManagerId { get; set; }
            public string ManagerName { get; set; }
        }

        public ActionResult Index(string login)
        {
            employee = AxdEntity_EmplTable_1.ConstructEmployee(login, "YIAC");
            if (employee == null)
                employee = AxdEntity_EmplTable_1.ConstructEmployee(login, "PAY");

            AppraisalAdmin appraisalAdmins = db.AppraisalAdmins.Find(employee.EmplId);

            return View(appraisalAdmins);
        }

        public ActionResult EmployeeList(string ORG)
        {
            ViewBag.ORGANIZATION = new SelectList(AxdEntity_EmplTable_1.ConstructEmployeeList().Select(st => st.OrganizationUnitName == null ? "None" : st.OrganizationUnitName).Distinct().OrderBy(OrganizationUnitName => OrganizationUnitName).ToList());
            if (ORG != null)
            {
                if (ORG != "Select all" && ORG != "")
                {

                    employeeList = new List<EmpListReport>();
                    employeeList = (from emp in (AxdEntity_EmplTable_1.ConstructEmployeeList().Where(st => st.OrganizationUnitName == ORG))
                                    select new EmpListReport()
                                    {
                                        EmplId = emp.EmplId,
                                        EmplName = emp.Name,
                                        EmplOrganization = emp.OrganizationUnitName,
                                        EmplPosition = emp.Title,
                                        JoinDate = emp.JoinDate,
                                        ManagerId = (emp.Manager == null ? "" : emp.Manager.EmplId),
                                        ManagerName = (emp.Manager == null ? "" : emp.Manager.Name),
                                    }).ToList();

                    ViewData["EmpList"] = employeeList;
                    return View();
                }
                else
                {

                    employeeList = new List<EmpListReport>();
                    employeeList = (from emp in (AxdEntity_EmplTable_1.ConstructEmployeeList())
                                    select new EmpListReport()
                                    {
                                        EmplId = emp.EmplId,
                                        EmplName = emp.Name,
                                        EmplOrganization = emp.OrganizationUnitName,
                                        EmplPosition = emp.Title,
                                        JoinDate = emp.JoinDate,
                                        ManagerId = (emp.Manager == null ? "" : emp.Manager.EmplId),
                                        ManagerName = (emp.Manager == null ? "" : emp.Manager.Name),
                                    }).ToList();

                    ViewData["EmpList"] = employeeList;
                    return View();

                }
            }
            return View();
        }

        public ActionResult ObjAppStatusRpt()
        {
            return View();
        }

        public ActionResult TrainRpt(string ORG, int YR = 0)
        {
            ViewBag.ORGANIZATION = new SelectList(AxdEntity_EmplTable_1.ConstructEmployeeList().Select(st => st.OrganizationUnitName == null ? "None" : st.OrganizationUnitName).Distinct().OrderBy(OrganizationUnitName => OrganizationUnitName).ToList());
            ViewBag.YEAR = new SelectList(db.AppraisalStatusYears.Select(st => st.Year).Distinct().OrderBy(Year => Year).ToList());
            DateTime targetDate = Convert.ToDateTime((YR + 1) + "-01-01");

            if (ORG != null)
            {
                if (ORG != "Select all" && ORG != "")
                {
                    using (YIACOAPPSDBEntities dbContext = new YIACOAPPSDBEntities())
                    {
                        List<DevReport> DevQuery = new List<DevReport>();

                        DevQuery = (from emp in (AxdEntity_EmplTable_1.ConstructEmployeeList().Where(st => st.OrganizationUnitName == ORG))
                                    join APP in db.Appraisals.Where(year => year.Year == YR)
                                     on emp.EmplId equals APP.EmplId
                                    join APD in db.AppraisalDevelopmentPlans
                                       on APP.AppraisalId equals APD.AppraisalId
                                    where APD.TargetDate >= targetDate
                                    select new DevReport()
                                    {
                                        AppraisalId = APD.AppraisalId,
                                        EmplId = emp.EmplId,
                                        EmplName = emp.Name,
                                        EmplOrganization = emp.OrganizationUnitName,
                                        EmplPosition = emp.TitleNameEN,
                                        DevelopmentNeeds = APD.DevelopmentNeeds,
                                        DevelopmentNeedsText = APD.DevelopmentNeedsText,
                                        TargetDate = APD.TargetDate.ToString(),
                                        ActionPlan = APD.ActionPlan,
                                   }).ToList();

                        ViewData["DevRpt"] = DevQuery;
                        return View();
                    }
                }
                else
                {
                    using (YIACOAPPSDBEntities dbContext = new YIACOAPPSDBEntities())
                    {
                        List<DevReport> DevQuery = new List<DevReport>();
                        
                        DevQuery = (from emp in (AxdEntity_EmplTable_1.ConstructEmployeeList())
                                    join APP in db.Appraisals.Where(year => year.Year == YR)
                                       on emp.EmplId equals APP.EmplId
                                    join APD in db.AppraisalDevelopmentPlans
                                       on APP.AppraisalId equals APD.AppraisalId
                                       where APD.TargetDate >= targetDate
                                    select new DevReport()
                                    {
                                        AppraisalId = APD.AppraisalId,
                                        EmplId = emp.EmplId,
                                        EmplName = emp.Name,
                                        EmplOrganization = emp.OrganizationUnitName,
                                        EmplPosition = emp.TitleNameEN,
                                        DevelopmentNeeds = APD.DevelopmentNeeds,
                                        DevelopmentNeedsText = APD.DevelopmentNeedsText,
                                        TargetDate = APD.TargetDate.ToString(),
                                        ActionPlan = APD.ActionPlan,
                                    }).ToList();

                        ViewData["DevRpt"] = DevQuery;
                        return View();
                    }
                }
            }
            else return View();
        }

        public ActionResult AppRpt(string ORG, int YR = 0)
        {
            ViewBag.ORGANIZATION = new SelectList(AxdEntity_EmplTable_1.ConstructEmployeeList().Select(st => st.OrganizationUnitName == null ? "None" : st.OrganizationUnitName).Distinct().OrderBy(OrganizationUnitName => OrganizationUnitName).ToList());
            ViewBag.YEAR = new SelectList(db.AppraisalStatusYears.Select(st => st.Year).Distinct().OrderBy(Year => Year).ToList());
            if (ORG != null)
            {
                if (ORG != "Select all" && ORG != "")
                {
                    using (YIACOAPPSDBEntities dbContext = new YIACOAPPSDBEntities())
                    {
                        Query = new List<EmpReport>();

TST YIACO HR/Employee Appraisal/Controllers/AppraisalStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Employee_Appraisal.Models;

namespace Employee_Appraisal.Controllers
{
    public class AppraisalStatusController : Controller
    {
        private YIACOAPPSDBEntities db = new YIACOAPPSDBEntities();

        // GET: /AppraisalStatus/
        public ActionResult Index()
        {
            return View(db.AppraisalStatusYears.ToList());
        }

        // GET: /AppraisalStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppraisalStatusYear appraisalstatus = db.AppraisalStatusYears.Find(id);
            if (appraisalstatus == null)
            {
                return HttpNotFound();
            }
            return View(appraisalstatus);
        }

        // GET: /AppraisalStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /AppraisalStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Year,Status")] AppraisalStatusYear appraisalstatus)
        {
            if (ModelState.IsValid)
            {
                db.AppraisalStatusYears.Add(appraisalstatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(appraisalstatus);
        }

        // GET: /AppraisalStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppraisalStatusYear appraisalstatus = db.AppraisalStatusYears.Find(id);
            if (appraisalstatus == null)
            {
                return HttpNotFound();
            }
            return View(appraisalstatus);
        }

        // POST: /AppraisalStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Year,Status")] AppraisalStatusYear appraisalstatus)
        {
            if (ModelState.IsValid)
            {
                List<Appraisal> appraisals = db.Appraisals.Where(yr => yr.Year == appraisalstatus.Year).ToList();
                int newStatus;

                if (appraisalstatus.Status == 0)
                    newStatus = 1;
                else
                    newStatus = 0;

                for(int i = 0; i < appraisals.Count(); i++)
                {
                    appraisals[i].Status = newStatus;
                }

                foreach (var item in appraisals)
                {
                    db.Entry(item).State = EntityState.Modified;
                }                

                db.Entry(appraisalstatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appraisalstatus);
        }

        // GET: /AppraisalStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppraisalStatusYear appraisalstatus = db.AppraisalStatusYears.Find(id);
            if (appraisalstatus == null)
            {
                return HttpNotFound();
            }
            return View(appraisalstatus);
        }

        // POST: /AppraisalStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AppraisalStatusYear appraisalstatus = db.AppraisalStatusYears.Find(id);
            db.AppraisalStatusYears.Remove(appraisalstatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TST YIACO HR/Employee Appraisal/Views/AppraisalReports/AppRpt.cshtml
@{
    ViewBag.Title = "AppRpt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta http-equiv="content-type" content="text/plain; charset=UTF-8" />

<h2>Appraisal Report</h2>

@Html.ActionLink("Back To List", "Index", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) })

<br /><br />

<table class="table">
    <tr>
        <th width="10">
            Organization
        </th>
        <td>
            @Html.DropDownList("ORGANIZATION", ViewBag.ORGANIZATION as SelectList, "Select all")
        </td>
        <th width="10">
            Year
        </th>
        <td>
            @Html.DropDownList("YEAR", ViewBag.YEAR as SelectList)
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Search" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var ORG = $('#ORGANIZATION').val();
                    var YR = $('#YEAR').val();
                    var path = '@Url.Content("~/AppraisalReports/AppRpt")' + "?ORG=" + ORG + "&YR=" + YR
                    window.open(path, '_self');
                });
            </script>
        </td>
    </tr>
</table>
<p>
    <a href="#" onclick="fnExcelReport()">Export To Excel</a>
    <script type="text/javascript">
        function fnExcelReport() {
            var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
            var textRange; var j = 0;
            tab = document.getElementById('tbExport'); // id of table

            for (j = 0 ; j < tab.rows.length ; j++) {
                tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
                //tab_text=tab_text+"</tr>";
            }

            tab_text = tab_text + "</table>";
            tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
            tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
            tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html", "replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
            }
            else                 //other browser not tested on IE 11
                sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));

            return (sa);
        }
    </script>
    @*@Html.ActionLink("Export To Excel", "ExportToExcel", "AppraisalReports")*@
</p>
<table id="tbExport" class="table">
    <tr>
        <th>

        </th>
        <th>
            EMPLOYEE ID
        </th>
        <th>
            Name
        </th>
        <th>
            ORGANIZATION
        </th>
        <th>
            POSITION
        </th>
        <th>
            FUNCTIONAL COMPETENCY
        </th>
        <th>
            CORE COMPETENCY
        </th>
        <th>
            RESPONSIBILTY
        </th>
        <th>
            SALES TARGET
        </th>
        <th>
            TOTAL SCORE
        </th>
        <th>
            LEGEND
        </th>
    </tr>

    @if (ViewData["AppRpt"] != null)
    {
        foreach (var item in (dynamic)(ViewData["AppRpt"]))
        {
            <tr>
                <td>
                    @Html.ActionLink("View Report", "Details", "Appraisals", new { id = item.AppraisalId, Delts = "YES" }, new { target = "blank" })
                </td>
                <td>
                    @item.EmplId
                </td>
                <td>
                    @item.EmplName
                </td>
                <td>
                    @item.EmplOrganization
                </td>
                <td>
                    @item.EmplPosition
                </td>
                <td>
                    @item.COM%
                </td>
                <td>
                    @item.RESP%
                </td>
                <td>
                    @item.ADMN%
                </td>
                <td>
                    @item.SALES%
                </td>
                <td>
                    @item.TOTAL%
                </td>
                @if (item.TOTAL >= 0 && item.TOTAL < 60.0)
                {
                    <td>Below Expecation</td>
                }
                else if (item.TOTAL >= 60.0 && item.TOTAL < 80.0)
                {
                    <td>Needs Improvement</td>
                }
                else if (item.TOTAL >= 80.0 && item.TOTAL < 109.0)
                {
                    <td>Meets expectations</td>
                }
                else if (item.TOTAL >= 109.0 && item.TOTAL < 115.0)
                {
                    <td>Exceeds Expectation</td>
                }
                else if (item.TOTAL >= 115.0 && item.TOTAL <= 120.0)
                {
                    <td>Outstanding</td>
                }
                else
                {
                    <td>Not Determind</td>
                }
            </tr>
        }
    }


</table>

@*<script>
    function ExportToExcel() {
        $.ajax({
            type: "POST",
            url: "../../AppraisalReports/ExportToExcel",
            data: "{RedeemData: " + JSON.stringify('@Html.Raw(Json.Encode(ViewData["AppRpt"]))') + "}",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                javascript: history.go(-1);
            }
        });
    }
</script>*@

TST YIACO HR/Employee Appraisal/Views/AppraisalReports/EmplAppRpt.cshtml
@{
    ViewBag.Title = "EmplAppRpt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Appraisal Report</h2>

@Html.ActionLink("Back To List", "Index", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) })

<br /><br />

<table class="table">
    <tr>
        <th width="150">
            Employee ID:
        </th>
        <td>
            <input type="text" name="EMPLID" id="EMPLID" />
        </td>
        <th width="10">
            Year
        </th>
        <td>
            @Html.DropDownList("YEAR", ViewBag.YEAR as SelectList)
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Show" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var EMPID = $('#EMPLID').val();
                    var YR = $('#YEAR').val();
                    var path = '@Url.Content("~/AppraisalReports/EmplAppRpt")' + "?emplId=" + EMPID + "&YR=" + YR
                    window.open(path, '_self');
                });
            </script>
        </td>
    </tr>
</table>
<table class="table">
    <tr>
        <th>

        </th>
        <th>
            EMPLOYEE ID
        </th>
        <th>
            Name
        </th>
        <th>
            ORGANIZATION
        </th>
        <th>
            POSITION
        </th>
    </tr>

    @if (ViewData["EmplAppRpt"] != null)
    {
        foreach (var item in (dynamic)(ViewData["EmplAppRpt"]))
        {
            <tr>
                <td>
                    @Html.ActionLink("View Report", "Details", "Appraisals", new { id = item.AppraisalId, Delts = "YES" }, new { target = "blank" })
                </td>
                <td>
                    @item.EmplId
                </td>
                <td>
                    @item.EmplName
                </td>
                <td>
                    @item.EmplOrganization
                </td>
                <td>
                    @item.EmplPosition
                </td>
            </tr>
        }
    }


</table>

TST YIACO HR/Employee Appraisal/Views/AppraisalReports/EmployeeList.cshtml
@{
    ViewBag.Title = "EmployeeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Employees List</h2>

@Html.ActionLink("Back To List", "Index", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) })

<br /><br />

<table class="table">
    <tr>
        <th width="10">
            Organization
        </th>
        <td>
            @Html.DropDownList("ORGANIZATION", ViewBag.ORGANIZATION as SelectList, "Select all")
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Search" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var ORG = $('#ORGANIZATION').val();
                    var path = '@Url.Content("~/AppraisalReports/EmployeeList")' + "?ORG=" + ORG
                    window.open(path, '_self');
                });
            </script>

        </td>
    </tr>
</table>
<p>
    <a href="#" onclick="fnExcelReport()">Export To Excel</a>
    <script type="text/javascript">
        function fnExcelReport() {
            var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
            var textRange; var j = 0;
            tab = document.getElementById('tbExport'); // id of table

            for (j = 0 ; j < tab.rows.length ; j++) {
                tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
                //tab_text=tab_text+"</tr>";
            }

            tab_text = tab_text + "</table>";
            tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
            tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
            tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html", "replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
            }
            else                 //other browser not tested on IE 11
                sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));

            return (sa);
        }
    </script>
    @*@Html.ActionLink("Export To Excel", "ExportEmpToExcel", "AppraisalReports")*@
</p>
<table id="tbExport" class="table">
    <tr>
        <th>
            EMPLOYEE ID
        </th>
        <th>
            NAME
        </th>
        <th>
            ORGANIZATION
        </th>
        <th>
            POSITION
        </th>
        <th>
            JOIN DATE
        </th>
        <th>
            MANAGER ID
        </th>
        <th>
            MANAGER NAME
        </th>
    </tr>
    @if (ViewData["EmpList"] != null)
    {
        foreach (var item in (dynamic)ViewData["EmpList"])
        {
            <tr>
                <td>
                    @item.EmplId
                </td>
                <td>
                    @item.EmplName
                </td>
                <td>
                    @item.EmplOrganization
                </td>
                <td>
                    @item.EmplPosition
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.JoinDate)
                </td>
                <td>
                    @item.ManagerId
                </td>
                <td>
                    @item.ManagerName
                </td>
            </tr>
        }
    }


</table>

TST YIACO HR/Employee Appraisal/Views/AppraisalReports/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reports</h2>

@if (Model != null)
{
    if (Model.Admin != 0)
    {
        <table class="table">
            <tr>
                <th>
                    @*<a href="http://www.yahoo.com" target="_blank"><span>Employees List</span></a>*@
                    @Html.ActionLink("Employees List", "EmployeeList")
                </th>
            </tr>
            <tr>
                <th>
                    @Html.ActionLink("Employees Appraisals List", "EmplAppRpt")
                </th>
            </tr>
            <tr>
                <th>
                    @Html.ActionLink("Objectives or Appraisal Status", "ObjAppStatusRpt")
                </th>
            </tr>
            <tr>
                <th>
                    @Html.ActionLink("Training Report", "TrainRpt")
                </th>
            </tr>
            <tr>
                <th>
                    @Html.ActionLink("Appraisal Report", "AppRpt")
                </th>
            </tr>
            <tr>
                <th>
                    @Html.ActionLink("Add/Open/Close Appraisal Year", "Index", "AppraisalStatus")
                </th>
            </tr>
        </table>
    }
    else
    {
        <p>
            You don't permission to open this page. Contact HR department.
        </p>
    }
}
else
{
    <p>
        You don't permission to open this page. Contact HR department.
    </p>
}

TST YIACO HR/Employee Appraisal/Views/AppraisalReports/ObjAppStatusRpt.cshtml
@model Employee_Appraisal.Models.Appraisal
    
@{
    ViewBag.Title = "ObjAppStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Objectives or Appraisals Status Reports</h2>

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Objectives Status", "ObjStatus", "ObjAppStatusRpt")
        </th>
    </tr>
    <tr>
        <th>
            @Html.ActionLink("Appraisal Status", "AppStatus", "ObjAppStatusRpt")
        </th>
    </tr>
    <tr>
        <th>
            @Html.ActionLink("Total Appraisal Status", "AppTotalStatus", "ObjAppStatusRpt")
        </th>
    </tr>
</table>
@Html.ActionLink("Back To List", "Index", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) })