TST YIACO HR/Employee Appraisal/Controllers/ObjAppStatusRptController.cs
using Employee_Appraisal.AIFEmployee;
using Employee_Appraisal.AIFRepRel;
using Employee_Appraisal.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Employee_Appraisal.Controllers
{
    public class ObjAppStatusRptController : Controller
    {
        private YIACOAPPSDBEntities db = new YIACOAPPSDBEntities();
        List<ObjReport> Objquery = new List<ObjReport>();
        List<AppReport> Appquery = new List<AppReport>();
        List<AppReport> RedeemAppData = new List<AppReport>();
        List<AppTotalReport> AppTotalquery = new List<AppTotalReport>();

        public class ObjReport
        {
            public string managerId { get; set; }
            public string managerName { get; set; }
            public int StaffNo { get; set; }
            public int Created { get; set; }
            public int NotCreated { get; set; }
            public int? Completed { get; set; }
            public int? NotCompleted { get; set; }
            public int? Accepted { get; set; }
            public int? Rejected { get; set; }
            public int? NotViewed { get; set; }
        }

        public class AppTotalReport
        {
            public string managerId { get; set; }
            public string managerName { get; set; }
            public int StaffNo { get; set; }
            public int Created { get; set; }
            public int NotCreated { get; set; }
            public int? Completed { get; set; }
            public int? NotCompleted { get; set; }
            public int? Accepted { get; set; }
            public int? Rejected { get; set; }
            public int? NotViewed { get; set; }
        }

        public class AppReport
        {
            public string managerId { get; set; }
            public string managerName { get; set; }
            public string empId { get; set; }
            public string empName { get; set; }
            public string civilId { get; set; }
            public DateTime joinDate { get; set; }
            public string org { get; set; }
            public string position { get; set; }
            public string IsCreated { get; set; }
            public string IsCompleted { get; set; }
            public string IsAccepted { get; set; }
        }

        public List<AxdEntity_SysCompanyRepRel_1> getReportingRelationships()
        {
            EmplRepRelServiceClient client = new EmplRepRelServiceClient();

            OperationContextScope o = new OperationContextScope(client.InnerChannel);

            AIFRepRel.QueryCriteria qc = new AIFRepRel.QueryCriteria();

            AxdEmplRepRel emplRepRel = new AxdEmplRepRel();

            qc.CriteriaElement = new AIFRepRel.CriteriaElement[1];
            qc.CriteriaElement[0] = new AIFRepRel.CriteriaElement();
            qc.CriteriaElement[0].DataSourceName = "SysCompanyRepRel_1";
            qc.CriteriaElement[0].Operator = AIFRepRel.Operator.NotEqual;
            qc.CriteriaElement[0].FieldName = "ReportsTo";
            qc.CriteriaElement[0].Value1 = "000000";

            try
            {
                emplRepRel = client.find(qc);

                if (emplRepRel != null)
                {
                    return emplRepRel.SysCompanyRepRel_1.ToList();
                }
                return null;
            }
            catch (Exception aifException)
            {
                return null;
            }
            finally
            {
                client.Close();
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObjStatus(string ORG, int YR = 0)
        {
            ViewBag.ORGANIZATION = new SelectList(AxdEntity_EmplTable_1.ConstructEmployeeList().Select(st => st.OrganizationUnitName == null ? "None" : st.OrganizationUnitName).Distinct().OrderBy(OrganizationUnitName => OrganizationUnitName).ToList());
            ViewBag.YEAR = new SelectList(db.AppraisalStatusYears.Select(st => st.Year).Distinct().OrderBy(Year => Year).ToList());

            List<ObjReport> reportResult = new List<ObjReport>();
            List<AxdEntity_SysCompanyRepRel_1> Employees = getReportingRelationships().ToList();

            if (ORG != null)
            {
                if (ORG != "Select all" && ORG != "")
                    Employees = getReportingRelationships().Where(employee => employee.Email == ORG).ToList();
            }
            using (YIACOAPPSDBEntities dbContext = new YIACOAPPSDBEntities())
            {
                List<Appraisal> Appraisals = dbContext.Appraisals.Where(year => year.Year == YR).ToList();
                List<string> Managers = Employees.Select(employee => employee.ReportsTo).Distinct().ToList();

                for (int i = 0; i < Managers.Count(); i++)
                {
                    if (Managers[i] != null)
                    {
                        reportResult.Add(new ObjReport()
                        {
                            managerId = Managers[i].ToString(),
                            managerName = (AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "YIAC") == null ? AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "PAY") == null ? "" : AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "PAY").Name : AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "YIAC").Name),
                            StaffNo = Employees.Count(empl => empl.ReportsTo == Managers[i]),
                            Created = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 0).Count(),
                            NotCreated = (Employees.Count(empl => empl.ReportsTo == Managers[i])) - (Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 0).Count()),
                            Completed = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 1).Count(),
                            NotCompleted = (Appraisals.Where(app => app.AppraiserId == Managers[i]).Count()) - (Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 1).Count()),
                            Accepted = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage == 2).Count(),
                            Rejected = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage == 3).Count(),
                            //NotViewed = ((row.Select(employeeStaff => employeeStaff.EmplId).Count()) - row.Where(o => o.AcceptObjectives == 1).Sum(accp => accp.AcceptObjectives) - row.Where(o => o.AcceptObjectives == 0).Sum(accp => accp.AcceptObjectives))
                        });
                    }
                }
                ViewData["ObjStat"] = reportResult;

                return View();
            }
        }

        public ActionResult AppTotalStatus(string ORG)
        {
            int YR = DateTime.Now.Year;
            //if (DateTime.Now.Month == 1)
            //    YR = DateTime.Now.Year - 1;
            ViewBag.ORGANIZATION = new SelectList(AxdEntity_EmplTable_1.ConstructEmployeeList().Select(st => st.OrganizationUnitName == null ? "None" : st.OrganizationUnitName).Distinct().OrderBy(OrganizationUnitName => OrganizationUnitName).ToList());
            ViewBag.YEAR = new SelectList(db.AppraisalStatusYears.Select(st => st.Year).Distinct().OrderBy(Year => Year).ToList());

            List<AppTotalReport> reportResult = new List<AppTotalReport>();
            List<AxdEntity_SysCompanyRepRel_1> Employees = getReportingRelationships().ToList();

            if (ORG != null)
            {
                if (ORG != "Select all" && ORG != "")
                    Employees = getReportingRelationships().Where(employee => employee.Email == ORG).ToList();
            }

            using (YIACOAPPSDBEntities dbContext = new YIACOAPPSDBEntities())
            {
                List<string> Managers = Employees.Select(employee => employee.ReportsTo).Distinct().ToList();
                List<Appraisal> Appraisals = dbContext.Appraisals.Where(year => year.Year == YR).ToList();

                for (int i = 0; i < Managers.Count(); i++)
                {
                    if (Managers[i] != null)
                    {
                        reportResult.Add(new AppTotalReport()
                            {
                                managerId = Managers[i].ToString(),
                                managerName = (AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "YIAC") == null ? AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "PAY") == null ? "" : AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "PAY").Name : AxdEntity_EmplTable_1.ConstructEmployeeById(Managers[i].ToString(), "YIAC").Name),
                                StaffNo = Employees.Count(empl => empl.ReportsTo == Managers[i]),
                                Created = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 4).Count(),
                                NotCreated = (Employees.Count(empl => empl.ReportsTo == Managers[i])) - (Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 4).Count()),
                                Completed = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 5).Count(),
                                NotCompleted = (Appraisals.Where(app => app.AppraiserId == Managers[i]).Count()) - (Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage >= 5).Count()),
                                Accepted = Appraisals.Where(app => app.AppraiserId == Managers[i] && app.Stage == 6).Count(),

TST YIACO HR/Employee Appraisal/Views/ObjAppStatusRpt/AppStatus.cshtml
@{
    ViewBag.Title = "AppStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Appraisals Status</h2>

@Html.ActionLink("Back To List", "Index", "AppraisalReports/ObjAppStatusRpt")
<br /><br />

<table class="table">
    <tr>
        <th width="10">
            Organization
        </th>
        <td>
            @Html.DropDownList("ORGANIZATION", ViewBag.ORGANIZATION as SelectList, "Select all")
        </td>
        <th width="10">
            Year
        </th>
        <td>
            @Html.DropDownList("YEAR", ViewBag.YEAR as SelectList)
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Search" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var ORG = $('#ORGANIZATION').val();
                    var YR = $('#YEAR').val();
                    var path = '@Url.Content("~/ObjAppStatusRpt/AppStatus")' + "?ORG=" + ORG + "&YR=" + YR
                    window.open(path, '_self');
                });
            </script>

        </td>
    </tr>
</table>
<p>
    <a href="#" onclick="fnExcelReport()">Export To Excel</a>
    <script type="text/javascript">
        function fnExcelReport() {
            var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
            var textRange; var j = 0;
            tab = document.getElementById('tbExport'); // id of table

            for (j = 0 ; j < tab.rows.length ; j++) {
                tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
                //tab_text=tab_text+"</tr>";
            }

            tab_text = tab_text + "</table>";
            tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
            tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
            tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html", "replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
            }
            else                 //other browser not tested on IE 11
                sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));

            return (sa);
        }
    </script>
    @*@Html.ActionLink("Export To Excel", "ExportAppToExcel", "ObjAppStatusRpt")*@
</p>
<table id="tbExport" class="table">
    <tr>
        <th style="font-size: x-small">
            EMPLOYEE ID
        </th>
        <th style="font-size: x-small">
            NAME
        </th>
        <th style="font-size: x-small">
            CIVIL ID
        </th>
        <th style="font-size: x-small">
            JOIN DATE
        </th>
        <th style="font-size: x-small">
            ORGANIZATION
        </th>
        <th style="font-size: x-small">
            POSITION
        </th>
        <th style="font-size: x-small">
            MANAGER ID
        </th>
        <th style="font-size: x-small">
            MANAGER NAME
        </th>
        <th style="font-size: x-small">
            IS CREATED
        </th>
        <th style="font-size: x-small">
            IS COMPLETED
        </th>
        <th style="font-size: x-small">
            IS ACCEPTED
        </th>
    </tr>

    @if (ViewData["AppStat"] != null)
    {
        foreach (var item in (dynamic)ViewData["AppStat"])
        {
            <tr>
                <td>
                    @item.empId
                </td>
                <td>
                    @item.empName
                </td>
                <td>
                    @item.civilId
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.joinDate)
                </td>
                <td>
                    @item.org
                </td>
                <td>
                    @item.position
                </td>
                <td>
                    @item.managerId
                </td>
                <td>
                    @item.managerName
                </td>
                <td>
                    @item.IsCreated
                </td>
                <td>
                    @item.IsCompleted
                </td>
                <td>
                    @item.IsAccepted
                </td>
            </tr>
        }
    }
</table>

TST YIACO HR/Employee Appraisal/Views/ObjAppStatusRpt/AppTotalStatus.cshtml
@{
    ViewBag.Title = "AppStatusTotal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Appraisals Status</h2>

@Html.ActionLink("Back To List", "Index", "AppraisalReports/ObjAppStatusRpt")
<br /><br />

<table class="table">
    <tr>
        <th width="10">
            Organization
        </th>
        <td>
            @Html.DropDownList("ORGANIZATION", ViewBag.ORGANIZATION as SelectList, "Select all")
        </td>
        <th width="10">
            Year
        </th>
        <td>
            @Html.DropDownList("YEAR", ViewBag.YEAR as SelectList)
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Search" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var ORG = $('#ORGANIZATION').val();
                    var YR = $('#YEAR').val();
                    var path = '@Url.Content("~/ObjAppStatusRpt/AppTotalStatus")' + "?ORG=" + ORG + "&YR=" + YR
                    window.open(path, '_self');
                });
            </script>

        </td>
    </tr>
</table>
<p>
    <a href="#" onclick="fnExcelReport()">Export To Excel</a>
    <script type="text/javascript">
        function fnExcelReport() {
            var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
            var textRange; var j = 0;
            tab = document.getElementById('tbExport'); // id of table

            for (j = 0 ; j < tab.rows.length ; j++) {
                tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
                //tab_text=tab_text+"</tr>";
            }

            tab_text = tab_text + "</table>";
            tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
            tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
            tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html", "replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
            }
            else                 //other browser not tested on IE 11
                sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));

            return (sa);
        }
    </script>
</p>
<table id="tbExport" class="table">
    <tr>
        <th style="font-size: x-small">
            MANAGER ID
        </th>
        <th style="font-size: x-small">
            MANAGER NAME
        </th>
        <th style="font-size: x-small">
            TOTAL NO OF STAFF
        </th>
        <th style="font-size: x-small">
            CREATED
        </th>
        <th style="font-size: x-small">
            NOT CREATED
        </th>
        <th style="font-size: x-small">
            COMPLETED
        </th>
        <th style="font-size: x-small">
            NOT COMPLETED
        </th>
        <th style="font-size: x-small">
            ACCEPTED
        </th>
        <th style="font-size: x-small">
            REJECTED
        </th>
        <th style="font-size: x-small">
            NOT VIEWED
        </th>
    </tr>

    @if (ViewData["AppTotalStat"] != null)
    {
        foreach (var item in (dynamic)ViewData["AppTotalStat"])
        {
            <tr>
                <td>
                    @item.managerId
                </td>
                <td>
                    @item.managerName
                </td>
                <td>
                    @item.StaffNo
                </td>
                <td>
                    @item.Created
                </td>
                <td>
                    @item.NotCreated
                </td>
                <td>
                    @item.Completed
                </td>
                <td>
                    @item.NotCompleted
                </td>
                <td>
                    @item.Accepted
                </td>
                <td>
                    @item.Rejected
                </td>
                <td>
                    @item.NotViewed
                </td>
            </tr>
        }
    }
</table>

TST YIACO HR/Employee Appraisal/Views/ObjAppStatusRpt/ObjStatus.cshtml
@{
    ViewBag.Title = "ObjStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Objectives Status</h2>

@Html.ActionLink("Back To List", "Index", "AppraisalReports/ObjAppStatusRpt")
<br /><br />

<table class="table">
    <tr>
        <th width="10">
            Organization
        </th>
        <td>
            @Html.DropDownList("ORGANIZATION", ViewBag.ORGANIZATION as SelectList, "Select all")
        </td>
        <th width="10">
            Year
        </th>
        <td>
            @Html.DropDownList("YEAR", ViewBag.YEAR as SelectList)
        </td>
        <td>
            <input id="SubmitName" type="submit" value="Search" />
            <script type="text/javascript">
                $('#SubmitName').click(function () {
                    var ORG = $('#ORGANIZATION').val();
                    var YR = $('#YEAR').val();
                    var path = '@Url.Content("~/ObjAppStatusRpt/ObjStatus")' + "?ORG=" + ORG + "&YR=" + YR
                    window.open(path, '_self');
                });
            </script>

        </td>
    </tr>
</table>
<p>
    <a href="#" onclick="fnExcelReport()">Export To Excel</a>
<script type="text/javascript">
    function fnExcelReport() {
        var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
        var textRange; var j = 0;
        tab = document.getElementById('tbExport'); // id of table

        for (j = 0 ; j < tab.rows.length ; j++) {
            tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
            //tab_text=tab_text+"</tr>";
        }

        tab_text = tab_text + "</table>";
        tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");//remove if u want links in your table
        tab_text = tab_text.replace(/<img[^>]*>/gi, ""); // remove if u want images in your table
        tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, ""); // reomves input params

        var ua = window.navigator.userAgent;
        var msie = ua.indexOf("MSIE ");

        if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
        {
            txtArea1.document.open("txt/html", "replace");
            txtArea1.document.write(tab_text);
            txtArea1.document.close();
            txtArea1.focus();
            sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
        }
        else                 //other browser not tested on IE 11
            sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));

        return (sa);
    }
</script>
@*@Html.ActionLink("Export To Excel", "ExportObjToExcel", "ObjAppStatusRpt")*@
</p>
<table id="tbExport" class="table">
    <tr>
        <th style="font-size: x-small">
            MANAGER ID
        </th>
        <th style="font-size: x-small">
            MANAGER NAME
        </th>
        <th style="font-size: x-small">
            TOTAL NO OF STAFF
        </th>
        <th style="font-size: x-small">
            CREATED
        </th>
        <th style="font-size: x-small">
            NOT CREATED
        </th>
        <th style="font-size: x-small">
            COMPLETED
        </th>
        <th style="font-size: x-small">
            NOT COMPLETED
        </th>
        <th style="font-size: x-small">
            ACCEPTED
        </th>
        <th style="font-size: x-small">
            REJECTED
        </th>
        <th style="font-size: x-small">
            NOT VIEWED
        </th>
    </tr>

    @if (ViewData["ObjStat"] != null)
    {
        foreach (var item in (dynamic)ViewData["ObjStat"])
        {
            <tr>
                <td>
                    @item.managerId
                </td>
                <td>
                    @item.managerName
                </td>
                <td>
                    @item.StaffNo
                </td>
                <td>
                    @item.Created
                </td>
                <td>
                    @item.NotCreated
                </td>
                <td>
                    @item.Completed
                </td>
                <td>
                    @item.NotCompleted
                </td>
                <td>
                    @item.Accepted
                </td>
                <td>
                    @item.Rejected
                </td>
                <td>
                    @item.NotViewed
                </td>
            </tr>
        }
    }
</table>