TST YIACO HR/Employee Appraisal/Controllers/AppraisalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Employee_Appraisal.Models;
using System.Data.Entity.Validation;
using Employee_Appraisal.AIFEmployee;
using Employee_Appraisal.AIFReportingRelationships;
using System.Diagnostics;
using Microsoft.Win32;

namespace Employee_Appraisal.Controllers
{
    public class CompetenciesToUpdate
    {
        public int AppraisalId { get; set; }
        public int QuestionId { get; set; }
        public string FieldValue { get; set; }
        public string ColumnToUpdate { get; set; }
        public string EmplID { get; set; }
    }

    public class AppraisalsController : Controller
    {
        private YIACOAPPSDBEntities db = new YIACOAPPSDBEntities();
        AxdEntity_EmplTable_1 employee;


        // GET: Appraisals
        public ActionResult Index()
        {
            employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "YIAC");

            if (employee == null)
                employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "PAY");

            var appraisal = db.Appraisals.Where(a => a.EmplId == employee.EmplId && (a.Deleted == 0 || a.Deleted == null));

            return View(appraisal.ToList());
        }

        // GET: Appraisals/Details/5
        public ActionResult Details(int? id, string Delts = null)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appraisal appraisal = db.Appraisals.Find(id);
            if (appraisal == null)
            {
                return HttpNotFound();
            }
            if (Delts != null)
            {
                ViewBag.Delts = "YES";
            }

            AppraisalLog appraisalLog = new AppraisalLog();

            appraisalLog.AppraisalId = appraisal.AppraisalId;
            appraisalLog.Appraisal = appraisal;
            if (appraisal.Stage == 1)
                appraisalLog.LogDescription = "Objectives Last Viewed.";
            else if (appraisal.Stage == 5)
                appraisalLog.LogDescription = "Appraisal Last Viewed.";
            appraisalLog.LogBy = this.User.Identity.Name.Remove(0, this.User.Identity.Name.LastIndexOf('\\') + 1);
            appraisalLog.LogAt = DateTime.Now;

            db.AppraisalLogs.Add(appraisalLog);

            return View(appraisal);
        }

        // GET: Appraisals/Create
        public ActionResult Create(string id)
        {
            if (DateTime.Now.Month == 1)
                ViewBag.Year = new SelectList(db.AppraisalStatusYears.Where(st => st.Status == 1).ToList(), "Year", "Year", (DateTime.Now.Year - 1));
            else
                ViewBag.Year = new SelectList(db.AppraisalStatusYears.Where(st => st.Status == 1).ToList(), "Year", "Year", DateTime.Now.Year);
            ViewBag.JobFamily = new SelectList(db.AppraisalJobFamilies.ToList(), "JobFamilyID", "JobFamilyName");
            ViewBag.EmplID = id;

            employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "YIAC");

            if (employee.EmplId == null)
                employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "PAY");

            ViewBag.AppraisarId = employee.EmplId;
            string emplName = "";
            emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(id, "YIAC").Name;
            if (emplName == null)
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(id, "PAY").Name;

            ViewBag.name = emplName;

            return View();
        }

        // POST: Appraisals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppraisalId,EmplId,AppraisalDate,Year,AppraisalRemarks,AppraisalFeedback,KPIFeedback,AppraiserId,EmplGroupId,FinancialGoal,Status,JobFamily,AcceptanceAppraisalDate,AcceptanceObjectivesDate")] Appraisal appraisal)
        {
            if (ModelState.IsValid)
            {
                Appraisal existAppraisal = db.Appraisals.Where(x => x.EmplId == appraisal.EmplId && x.Year == appraisal.Year && (x.Deleted == 0 || x.Deleted == null)).FirstOrDefault();
                if (existAppraisal == null)
                {
                    db.Appraisals.Add(appraisal);
                    db.SaveChanges();

                    AppraisalEmployee appraisalEmployee = new AppraisalEmployee();
                    for (int i = 1; i <= 5; i++)
                    {
                        appraisalEmployee.AppraisalId = appraisal.AppraisalId;
                        appraisalEmployee.EmplId = appraisal.EmplId;
                        appraisalEmployee.QuestionWeight = 20;
                        appraisalEmployee.QuestionCode = "C0" + i;
                        if (i == 1)
                            appraisalEmployee.QuestionText = "Clearly conveying information and ideas through a variety of media to individuals or groups in a manner that engages the audience and helps them understand and retain the message";
                        if (i == 2)
                            appraisalEmployee.QuestionText = "Taking prompt action to accomplish objectives; taking action to achieve goals beyond what is required; being proactive";
                        if (i == 3)
                            appraisalEmployee.QuestionText = "Making customers and their needs a primary focus of one’s actions; developing and sustaining productive customer relationships";
                        if (i == 4)
                            appraisalEmployee.QuestionText = "Accomplishing tasks by considering all areas involved, no matter how small; showing concern for all aspects of the job; accurately checking processes and tasks; being watchful over a period of time";
                        if (i == 5)
                            appraisalEmployee.QuestionText = "Adheres to the team’s expectations and guidelines; fulfills team responsibilities; demonstrates personal commitment to the team";

                        db.AppraisalEmployees.Add(appraisalEmployee);
                        db.SaveChanges();
                    }

                    AppraisalLog appraisalLog = new AppraisalLog();

                    appraisalLog.AppraisalId = appraisal.AppraisalId;
                    appraisalLog.Appraisal = appraisal;
                    appraisalLog.LogDescription = "Appraisal Created.";
                    appraisalLog.LogBy = this.User.Identity.Name.Remove(0, this.User.Identity.Name.LastIndexOf('\\') + 1);
                    appraisalLog.LogAt = DateTime.Now;

                    db.AppraisalLogs.Add(appraisalLog);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException e)
                    {
                        foreach (var eve in e.EntityValidationErrors)
                        {
                            Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                eve.Entry.Entity.GetType().Name, eve.Entry.State);
                            foreach (var ve in eve.ValidationErrors)
                            {
                                Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                    ve.PropertyName, ve.ErrorMessage);
                            }
                        }
                        throw;
                    }

                    return Redirect("~/Employees/Appraisals/" + appraisal.EmplId + "?name=" + appraisal.Employee.Name);
                }
                ViewBag.Error = "Can not create another appraisal for the same year to this employee.";
                ViewBag.Year = new SelectList(db.AppraisalStatusYears, "Year", "Year", appraisal.Year);
                ViewBag.JobFamily = new SelectList(db.AppraisalJobFamilies, "JobFamilyID", "JobFamilyName", appraisal.JobFamily);
                ViewBag.EmplID = appraisal.EmplId;
                employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "YIAC");
                if (employee.EmplId == null)
                    employee = AxdEntity_EmplTable_1.ConstructEmployee(this.User.Identity.Name, "PAY");
                ViewBag.AppraisarId = employee.EmplId;
                return View();
            }

            ViewBag.Year = new SelectList(db.AppraisalStatusYears, "Year", "Year", appraisal.Year);
            ViewBag.JobFamily = new SelectList(db.AppraisalJobFamilies.ToList(), "JobFamilyID", "JobFamilyName");
            return View(appraisal);
        }

        // GET: Appraisals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appraisal appraisal = db.Appraisals.Find(id);
            if (appraisal == null)
            {
                return HttpNotFound();
            }
            ViewBag.Year = new SelectList(db.AppraisalStatusYears, "Year", "Year", appraisal.Year);
            ViewBag.JobFamily = new SelectList(db.AppraisalJobFamilies, "JobFamilyID", "JobFamilyName", appraisal.JobFamily);
            return View(appraisal);
        }

        // POST: Appraisals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

TST YIACO HR/Employee Appraisal/Views/Appraisals/Create.cshtml
@model Employee_Appraisal.Models.Appraisal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div style="font-family: Arial; font-size: medium; font-weight: bold; color: red;">
            @ViewBag.Error
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Employee ID:</div>
            <div class="col-md-10">
                <div style="width: 100px;" class="form-control"> @ViewBag.EmplID</div>
                <div style="display: none;">@Html.TextBoxFor(model => model.EmplId, new { @class = "form-control", @Value = ViewBag.EmplID } )</div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <div style="display: none;">
                    @Html.TextBoxFor(model => model.AppraiserId, new { @class = "form-control", @Value = ViewBag.AppraisarId })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Year:</div>
            <div class="col-md-10">
                @Html.DropDownList("Year", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Job Family:</div>
            <div class="col-md-10">
                @Html.DropDownList("JobFamily", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JobFamily, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Apraisal Date:</div>
            <div class="col-md-10">
                <div style="width: 100px;" class="form-control">
                    @DateTime.Now.Date.ToString("dd/MM/yyyy")
                </div>
                <div style="display: none;">
                    @Html.TextBoxFor(model => model.AppraisalDate, new { @class = "form-control", @Value = DateTime.Now })
            </div>
            @Html.ValidationMessageFor(model => model.AppraisalDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div style="display: none;">
        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Appraisal Remarks:</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AppraisalRemarks, new { @class = "form-control", @Value = "." })
                @Html.ValidationMessageFor(model => model.AppraisalRemarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Appraisal Feedback:</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AppraisalFeedback, new { @class = "form-control", @Value = "." })
                @Html.ValidationMessageFor(model => model.AppraisalFeedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">.KPI Feedback:</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.KPIFeedback, new { @class = "form-control", @Value = "." })
                @Html.ValidationMessageFor(model => model.KPIFeedback, "", new { @class = "text-danger" })
            </div>

        </div>
    </div>
    <div class="form-group" style="display: none;">
        <div class="control-label col-md-2" style="font-weight: bold;">Employee Group:</div>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EmplGroupId, new { @class = "form-control", @Value = 0 })
            @Html.ValidationMessageFor(model => model.EmplGroupId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2" style="font-weight: bold;">Financial Goal:</div>
        <div class="col-md-10">
            @Html.DropDownList("FinancialGoal", new List<SelectListItem>{
                    new SelectListItem{ Text = "No", Value = "0"},
                    new SelectListItem{ Text = "Yes", Value = "1"}
                }, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FinancialGoal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="display: none;">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Status", new List<SelectListItem>{
                    new SelectListItem{ Text = "Open", Value = "0"},
                    new SelectListItem{ Text = "Close", Value = "1"}
                }, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
    <div>
        @Html.ActionLink("Back to List", "Appraisals", "Employees", new { id = ViewBag.EmplID, name = ViewBag.name }, null)
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TST YIACO HR/Employee Appraisal/Views/Appraisals/Delete.cshtml
@model Employee_Appraisal.Models.Appraisal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appraisal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmplId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmplId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppraisalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppraisalDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinancialGoal)
        </dt>

        @if (Model.FinancialGoal == 0)
        {
            <dd style="width:100px;">No</dd> }
        else
        {
            <dd style="width:100px;">Yes</dd> }

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        @if (Model.Status == 0)
        {
            <dd style="width:100px;">Open</dd> }
        else
        {
            <dd style="width:100px;">Closed</dd> }

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Appraisals", "Employees", new { id = Model.EmplId, name = Model.Employee.Name }, null)
        </div>
    }
</div>

TST YIACO HR/Employee Appraisal/Views/Appraisals/Edit.cshtml
@model Employee_Appraisal.Models.Appraisal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AppraisalId)

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Employee ID:</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmplId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.EmplId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Year:</div>
            <div class="col-md-10">
                @Html.DropDownList("Year", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Job Family:</div>
            <div class="col-md-10">
                @Html.DropDownList("JobFamily", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JobFamily, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Appraisal Date:</div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.AppraisalDate, new { @Value = Model.AppraisalDate.ToString("d"), @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.AppraisalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="display: none;">

            <div class="form-group">
                <div class="control-label col-md-2" style="font-weight: bold;">Appraisal Remarks:</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AppraisalRemarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AppraisalRemarks, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2" style="font-weight: bold;">Manager's Feedback:</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AppraisalFeedback, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AppraisalFeedback, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2" style="font-weight: bold;">KPI Feedback:</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KPIFeedback, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KPIFeedback, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2" style="font-weight: bold;">Appraiser Id:</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AppraiserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AppraiserId, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">
                Employee Group:
            </div>
            <div class="col-md-10">
                @Html.DropDownList("EmplGroupId", new List<SelectListItem>{
                    new SelectListItem{ Text = "Sales", Value = "1"},
                    new SelectListItem{ Text = "Admin", Value = "0"}
                }, new { @class = "form-control", @onchange = "GetFinancialGoal()" })
                @Html.ValidationMessageFor(model => model.EmplGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Financial Goal:</div>
            <div class="col-md-10">
                @Html.DropDownList("FinancialGoal", new List<SelectListItem>{
                    new SelectListItem{ Text = "Yes", Value = "1"},
                    new SelectListItem{ Text = "No", Value = "0"}
                }, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FinancialGoal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2" style="font-weight: bold;">Status:</div>
            @if (Model.Status == 0)
            {
                <div class="col-md-10">
                    @Html.DropDownList("Status", new List<SelectListItem>{
                    new SelectListItem{ Text = "Open", Value = "0"},
                    new SelectListItem{ Text = "Close", Value = "1"}
                }, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            }
            else
            {
                <div style="font-family: Arial; font-size: medium; color: red;">
                    This Appraisal is Closed, to open it please contact HR department.
                </div>
            }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Appraisals", "Employees", new { id = Model.EmplId, name = Model.Employee.Name }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function GetFinancialGoal() {
            var e = document.getElementById("EmplGroupId");
            var questiontext = e.options[e.selectedIndex].text;
            var f = document.getElementById("FinancialGoal");
            if (questiontext == "Sales") {
                f.value = 1;
                f.disabled = true;
            }
            else {
                f.value = 0;
                f.disabled = false
            }
        }
    </script>
}

TST YIACO HR/Employee Appraisal/Views/Appraisals/Index.cshtml
@model IEnumerable<Employee_Appraisal.Models.Appraisal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Appraisals</h2>

<table class="table">
    <tr>
        <th>
            Employee ID
        </th>
        <th>
            Appraisal Date
        </th>
        <th>
            Appraiser
        </th>
        <th>
            Employee Group
        </th>
        <th>
            Job Family
        </th>
        <th>
            Financial Goal
        </th>
        <th>
            Status
        </th>
        <th>
            Acceptance
        </th>
        <th>
            Year
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmplId)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.AppraisalDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppraiserId)
            </td>
            @if (item.EmplGroupId == 0)
            {
                <td style="width:100px;">Admin</td> }
            else
            {
                <td style="width:100px;">Sales</td> }
            <td>
                @Html.DisplayFor(modelItem => item.AppraisalJobFamily.JobFamilyName)
            </td>
            @if (item.FinancialGoal == 0)
            {
                <td style="width:100px;">No</td> }
            else
            {
                <td style="width:100px;">Yes</td> }
            @if (item.Status == 0)
            {
                <td style="width:100px;">Open</td> }
            else
            {
                <td style="width:100px;">Closed</td> }
            @if (item.Stage == 7)
            {
                <td style="width:100px;">Rejected</td> }
            else if (item.Stage == 6)
            {
                <td style="width:100px;">Accepted</td> }
            else if (item.Stage == 5)
            {
                <td style="width:100px;">Not Viewed</td> }
            else if (item.Stage <= 4)
            {
                <td style="width:100px;">Not Ready</td> }
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.AppraisalId })
            </td>
        </tr>
    }

</table>