TST YIACO HR/Employee Appraisal/Controllers/AppraisalDevelopmentPlanController.cs
using Employee_Appraisal.AIFEmployee;
using Employee_Appraisal.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Employee_Appraisal.Controllers
{
    public class AppraisalDevelopmentPlanController : Controller
    {
        private YIACOAPPSDBEntities db = new YIACOAPPSDBEntities();

        // GET: /AppraisalDevelopmentPlan/
        public ActionResult Index(int appraisalId, string name)
        {
            var development = db.AppraisalDevelopmentPlans.Where(a => a.AppraisalId == appraisalId);

            return View(development.ToList());
        }

        //
        // GET: /AppraisalDevelopmentPlan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /AppraisalDevelopmentPlan/Create
        public ActionResult Create(int AppraisalId, string DevelopmentNeedsCode, string selVal)
        {
            string emplName = "";

            ViewBag.NeedsCode = db.AppraisalQuestionGroups.Where(name => name.Name == DevelopmentNeedsCode).Select(l => l.GroupId).FirstOrDefault().ToString();

            selVal = ViewBag.NeedsCode;
            ViewBag.DevelopmentNeedsCode = new SelectList(db.AppraisalQuestionGroups.Where(typ => typ.TypeId == 5)
            .ToList(), "GroupId", "Name", DevelopmentNeedsCode);
            ViewBag.DevelopmentNeedsText = new SelectList(db.AppraisalQuestions
                .Where(desc => desc.QuestionGroup == selVal)
                .ToList(), "QuestionCode", "QuestionText");
            ViewBag.AppraisalId = AppraisalId;
            ViewBag.SelVal = selVal;
            ViewBag.DEVTXT = DevelopmentNeedsCode;
            emplName = "";
            emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
            if (emplName == null)
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;

            ViewBag.name = emplName;

            return View();
        }

        //
        // POST: /AppraisalDevelopmentPlan/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppraisalId,DevelopmentNeeds,DevelopmentNeedsText,TargetDate,ActionPlan")] AppraisalDevelopmentPlan appraisalDevelopmentPlan, string DevelopmentNeedsCode, string selVal)
        {
            string emplName = "";
            if (ModelState.IsValid)
            {
                try
                {
                    db.AppraisalDevelopmentPlans.Add(appraisalDevelopmentPlan);
                    db.SaveChanges();

                    emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
                    if (emplName == null)
                        emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;

                    return Redirect("~/Employees/Details/" + appraisalDevelopmentPlan.AppraisalId);
                }
                catch (Exception ex)
                {
                    return View();
                }
            }


            ViewBag.DevelopmentNeedsCode = new SelectList(db.AppraisalQuestionGroups.Where(typ => typ.TypeId == 5)
                .ToList(), "GroupId", "Name", DevelopmentNeedsCode);
            ViewBag.DevelopmentNeedsText = new SelectList(db.AppraisalQuestions
                .Where(desc => desc.QuestionGroup == DevelopmentNeedsCode)
                .ToList(), "QuestionCode", "QuestionText");
            ViewBag.AppraisalId = appraisalDevelopmentPlan.AppraisalId;
            ViewBag.SelVal = selVal;
            emplName = "";
            emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
            if (emplName == null)
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;

            ViewBag.name = emplName;
            return View();
        }

        //
        // GET: /AppraisalDevelopmentPlan/Edit/5
        public ActionResult Edit(int? id, string DevelopmentNeedsCode, string selVal)
        {
            string emplName;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppraisalDevelopmentPlan appraisalDevelopmentPlan = db.AppraisalDevelopmentPlans.Find(id);
            if (appraisalDevelopmentPlan == null)
            {
                return HttpNotFound();
            }

            ViewBag.NeedsCode = db.AppraisalQuestionGroups.Where(name => name.Name == DevelopmentNeedsCode).Select(l => l.GroupId).FirstOrDefault().ToString();

            try
            {
                ViewBag.NeedsTxtCode = db.AppraisalQuestions.Where(name => name.QuestionText == appraisalDevelopmentPlan.DevelopmentNeedsText).Select(l => l.QuestionCode).FirstOrDefault().ToString();
            }
            catch (Exception ex)
            {
                ViewBag.NeedsTxtCode = db.AppraisalQuestions.Where(name => name.QuestionText == "Others").Select(l => l.QuestionCode).FirstOrDefault().ToString();
                ViewBag.NeedsTxt = appraisalDevelopmentPlan.DevelopmentNeedsText;
            }

            selVal = ViewBag.NeedsCode;

            ViewBag.DevelopmentNeedsCode = new SelectList(db.AppraisalQuestionGroups.Where(typ => typ.TypeId == 5)
            .ToList(), "GroupId", "Name", ViewBag.NeedsCode);
            ViewBag.DevelopmentNeedsText = new SelectList(db.AppraisalQuestions
                .Where(desc => desc.QuestionGroup == selVal)
                .ToList(), "QuestionCode", "QuestionText", ViewBag.NeedsTxtCode);

            ViewBag.AppraisalId = appraisalDevelopmentPlan.AppraisalId;
            ViewBag.SelVal = selVal;
            ViewBag.DEVTXT = DevelopmentNeedsCode;

            emplName = "";
            emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
            if (emplName == null)
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;

            ViewBag.name = emplName;
            return View(appraisalDevelopmentPlan);
        }

        //
        // POST: /AppraisalDevelopmentPlan/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DevelopmentPlanId,AppraisalId,DevelopmentNeeds,DevelopmentNeedsText,TargetDate,ActionPlan")] AppraisalDevelopmentPlan appraisalDevelopmentPlan, string DevelopmentNeedsCode, string selVal)
        {
            string emplName;
            if (ModelState.IsValid)
            {
                db.Entry(appraisalDevelopmentPlan).State = EntityState.Modified;
                db.SaveChanges();
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
                if (emplName == null)
                    emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;
                return Redirect("~/Employees/Details/" + appraisalDevelopmentPlan.AppraisalId);
            }
            ViewBag.DevelopmentNeedsCode = new SelectList(db.AppraisalQuestionGroups.Where(typ => typ.TypeId == 5)
                .ToList(), "GroupId", "Name", DevelopmentNeedsCode);
            ViewBag.DevelopmentNeedsText = new SelectList(db.AppraisalQuestions
                .Where(desc => desc.QuestionGroup == DevelopmentNeedsCode)
                .ToList(), "QuestionCode", "QuestionText");
            ViewBag.AppraisalId = appraisalDevelopmentPlan.AppraisalId;
            ViewBag.SelVal = selVal;
            emplName = "";
            emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "YIAC").Name;
            if (emplName == null)
                emplName = AxdEntity_EmplTable_1.ConstructEmployeeById(db.Appraisals.Where(ap => ap.AppraisalId == appraisalDevelopmentPlan.AppraisalId).Select(l => l.EmplId).FirstOrDefault(), "PAY").Name;

            ViewBag.name = emplName;
            return View(appraisalDevelopmentPlan);
        }

        //
        // GET: /AppraisalDevelopmentPlan/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppraisalDevelopmentPlan appraisalDevelopmentPlan = db.AppraisalDevelopmentPlans.Find(id);
            if (appraisalDevelopmentPlan == null)
            {
                return HttpNotFound();
            }
            ViewBag.AppraisalId = appraisalDevelopmentPlan.AppraisalId;
            string emplName = "";

TST YIACO HR/Employee Appraisal/Views/Shared/_AppraisalDevelopmentPlan.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalDevelopmentPlan>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<h2>Development Plan</h2>
<table class="table">
    <tr>
        <th>
            Development Needs
        </th>
        <th>
            Target Date
        </th>
        <th>
            Action Plan
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DevelopmentNeeds)
                <br />
                @Html.DisplayFor(modelItem => item.DevelopmentNeedsText)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.TargetDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActionPlan)
            </td>
        </tr>
    }
</table>

TST YIACO HR/Employee Appraisal/Views/Shared/_AppraisalDevelopmentPlanEdit.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalDevelopmentPlan>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<table id="Dev"><tr><td height="30px;"></td></tr></table>

<h2>Development Plan</h2>
<table class="table">
    <tr>
        <th>
            Development Needs
        </th>
        <th>
            Target Date
        </th>
        <th>
            Action Plan
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DevelopmentNeeds)
                <br />
                @Html.DisplayFor(modelItem => item.DevelopmentNeedsText)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.TargetDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActionPlan)
            </td>
            @if (Model.FirstOrDefault().Appraisal.Stage == 4)
            {
                <td class="noprint">
                    @Html.ActionLink("Edit", "Edit", "AppraisalDevelopmentPlan", new { id = item.DevelopmentPlanId, DevelopmentNeedsCode = item.DevelopmentNeeds }, null) |
                    @Html.ActionLink("Delete", "Delete", "AppraisalDevelopmentPlan", new { id = item.DevelopmentPlanId }, null)
                </td>
            }
        </tr>
    }

</table>

<div class="noprint">
    @Html.ActionLink("Add Development Plan", "Create", "AppraisalDevelopmentPlan", new { AppraisalId = ViewData["AppraisalId"], DevelopmentNeedsCode = "Administrative Staff" }, null)
</div>

TST YIACO HR/Employee Appraisal/Views/Shared/_CoreCompetencies.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalEmployee>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<h2>Core Competencies</h2>

@if (Model.ToList().Count != 0)
{
    <br />
    <table class="table">
        <tr>
            <th>
                <div style="font-weight: bold; width: 120px;">Competency</div>
            </th>
            <th>
                <div style="font-weight: bold; width: 120px;">Weight</div>
            </th>
            <th>
                <div class="noprint">@Html.DisplayNameFor(model => model.Actual)</div>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score) %
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionText)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionWeight)
                </td>
                <td><div class="noprint">@Html.DisplayFor(modelItem => item.Actual)</div></td>
                <td>
                    <div class="COScore">@Html.DisplayFor(modelItem => item.Score)</div>
                </td>
            </tr>
        }
    </table>
    <table>
        <tr>
            <td style="font-family: Arial; font-size: medium; font-weight: bold;">
                Total Core Competencies Score:
                <input id="COTotalScore" type="text" value="0" readonly style="border:0; outline:none;" />
            </td>
        </tr>
    </table>
}

<div style="display: none;">
    @Html.TextBox("STAG", Model.FirstOrDefault().Appraisal.Stage.ToString(), new { @class = "form-control", @readonly = "readonly" })
</div>

TST YIACO HR/Employee Appraisal/Views/Shared/_CoreCompetenciesEdit.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalEmployee>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<h2>Core Competencies</h2>
@if (Model.ToList().Count != 0)
{
    <br />
    <table class="table">
        <tr>
            <th></th>
            <th></th>
            <th>
                <div style="font-weight: bold; width: 120px;">Competency</div>
            </th>
            <th>
                <div style="font-weight: bold; width: 120px;">Weight</div>
            </th>
            <th>
                <div class="noprint">@Html.DisplayNameFor(model => model.Actual)</div>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score) %
            </th>
            <th><div class="noprint">Action</div></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.AppraisalId, new { id = "key" })
                </td>
                <td>
                    @Html.HiddenFor(modelItem => item.QuestionId, new { id = "key2" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionText)
                </td>
                <td>
                    <div id="COQuestionWght" class="COQuestionWeight">@Html.DisplayFor(modelItem => item.QuestionWeight)</div>
                </td>
                <td><div id="COQuestionAc" class="COActual noprint">@Html.DisplayFor(modelItem => item.Actual)</div></td>
                <td>
                    <div class="COScore">@Html.DisplayFor(modelItem => item.Score)</div>
                </td>
                @if (Model.FirstOrDefault().Appraisal.Stage < 1)
                {
                    <td><div class="noprint">@Html.ActionLink("Delete", "Delete", "AppraisalEmployee", new { appraisalId = item.AppraisalId, emplId = item.EmplId, questionId = item.QuestionId }, null)</div></td>}
            </tr>
        }
    </table>
    <table>
        <tr>
            <td style="font-family: Arial; font-size: medium; font-weight: bold;">
                Total Core Competencies Score:
                <input id="COTotalScore" type="text" value="0" readonly style="border:0; outline:none;" />
            </td>
        </tr>
    </table>
}

<br />
@if (Model.ToList().Count < 5)
{
    <p>
        <div class="noprint">
            @Html.ActionLink("Add Core Competencies Objective",
                             "Create",
                             "AppraisalEmployee",
                             new
                             {
                                 AppraisalId = ViewData["AppraisalId"],
                                 emplId = ViewData["EmplId"],
                                 question = "COText",
                                 jobFamily = ViewData["JobFamily"]
                             },
                             null)
        </div>
    </p>
}
<div style="display: none;">
    @Html.TextBox("STAG", Model.FirstOrDefault().Appraisal.Stage.ToString(), new { @class = "form-control", @readonly = "readonly" })
</div>

TST YIACO HR/Employee Appraisal/Views/Shared/_FunctionalCompetencies.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalEmployee>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<script>
    var financialGoal = '@ViewData["FinancialGoal"]';
    var emplId = '@ViewData["EmplId"]';
</script>

<h2>Functional Competencies</h2>

@if (Model.ToList().Count != 0)
{
    <br />
    <table class="table">
        <tr>
            <th>
                <div style="font-weight: bold; width: 120px;">Competency</div>
            </th>
            <th>
                <div style="font-weight: bold; width: 120px;">Weight</div>
            </th>
            <th>
                <div class="noprint">@Html.DisplayNameFor(model => model.Actual)</div>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score) %
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionText)
                </td>
                <td>@Html.DisplayFor(modelItem => item.QuestionWeight)</td>
                <td><div class="noprint">@Html.DisplayFor(modelItem => item.Actual)</div></td>
                <td><div class="FNScore">@Html.DisplayFor(modelItem => item.Score)</div></td>
            </tr>
        }
    </table>
    <table>
        <tr>
            <td style="font-family: Arial; font-size: medium; font-weight: bold;">
                Total Functional Competencies Score:
                <input id="FNTotalScore" type="text" value="0" readonly style="border:0; outline:none;" />
            </td>
        </tr>
    </table>
}

<div style="display: none;">
    @Html.TextBox("STAG", Model.FirstOrDefault().Appraisal.Stage.ToString(), new { @class = "form-control", @readonly = "readonly" })
</div>

TST YIACO HR/Employee Appraisal/Views/Shared/_FunctionalCompetenciesEdit.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalEmployee>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<script>
    var financialGoal = '@ViewData["FinancialGoal"]';
    var emplId = '@ViewData["EmplId"]';
    var appraisalId = '@ViewData["AppraisalId"]';
    var acceptObjectives = '@ViewBag.AcceptObjectives';
</script>

<table id="Fun"><tr><td height="30px;"></td></tr></table>

<h2>Functional Competencies</h2>

@if (Model.ToList().Count != 0)
{
    <br />
    <table class="table">
        <tr>
            <th></th>
            <th></th>
            <th>
                <div style="font-weight: bold; width: 120px;">Competency</div>
            </th>
            <th>
                <div style="font-weight: bold; width: 120px;">Weight</div>
            </th>
            <th>
                <div class="noprint">@Html.DisplayNameFor(model => model.Actual)</div>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score) %
            </th>
            <th><div class="noprint">Action</div></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.AppraisalId, new { id = "key" })
                </td>
                <td>
                    @Html.HiddenFor(modelItem => item.QuestionId, new { id = "key2" })
                </td>
                <td>
                    <div id="FNQuestionTxt" class="FNQuestionText">
                        @Html.DisplayFor(modelItem => item.QuestionText)
                    </div>
                </td>
                <td><div id="FNQuestionWght" class="FNQuestionWeight">@Html.DisplayFor(modelItem => item.QuestionWeight)</div></td>
                <td><div id="FNQuestionAc" class="FNActual noprint">@Html.DisplayFor(modelItem => item.Actual)</div></td>
                <td><div class="FNScore">@Html.DisplayFor(modelItem => item.Score)</div></td>
                @if (Model.FirstOrDefault().Appraisal.Stage < 1)
                {
                <td><div class="noprint">@Html.ActionLink("Delete", "Delete", "AppraisalEmployee", new { appraisalId = item.AppraisalId, emplId = item.EmplId, questionId = item.QuestionId }, null)</div></td>}
            </tr>
        }
    </table>
    <table>
        <tr>
            <td style="font-family: Arial; font-size: medium; font-weight: bold;">
                Total Functional Competencies Score:
                <input id="FNTotalScore" type="text" value="0" readonly style="border:0; outline:none;" />
            </td>
        </tr>
    </table>
}

<br />
@if (Model.ToList().Count < 5)
{
    <p>
        <div class="noprint">
            @Html.ActionLink("Add Functional Competencies",
                             "Create",
                             "AppraisalEmployee",
                             new
                             {
                                 AppraisalId = ViewData["AppraisalId"],
                                 emplId = ViewData["EmplId"],
                                 jobFamily = ViewData["JobFamily"]
                             },
                            null)
        </div>
    </p>
}

TST YIACO HR/Employee Appraisal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title - Employee Performance Appraisal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #005596;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Performance Appraisal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("My Appraisal", "Index", "Appraisals")</li>
                    @* Added by wziadia *@
                    <li>@Html.ActionLink("My Employees", "Index", "Employees", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) }, null)</li>
                    <li>@Html.ActionLink("HR Reports", "Index", "AppraisalReports", new { login = User.Identity.Name.Substring(6, (User.Identity.Name.Length - 6)) }, null)</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Employee Performance Appraisal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Custom")
    @RenderSection("scripts", required: false)
</body>
</html>

TST YIACO HR/Employee Appraisal/Views/Shared/_OperationalObjectives.cshtml
@model IEnumerable<Employee_Appraisal.Models.AppraisalEmployee>

<style type="text/css" media="print">
    .noprint {
        display: none;
    }
</style>

<h2>Operational Objectives</h2>

@if (Model.ToList().Count != 0)
{
    <br />
    <table class="table">
        <tr>
            <th>
                <div style="font-weight: bold; width: 120px;">Objective</div>
            </th>
            <th>
                <div style="font-weight: bold; width: 120px;">Weight</div>
            </th>
            <th>
                <div class="noprint">@Html.DisplayNameFor(model => model.Actual)</div>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score) %
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionText)
                </td>
                <td>@Html.DisplayFor(modelItem => item.QuestionWeight)</td>
                <td><div class="noprint">@Html.DisplayFor(modelItem => item.Actual)</div></td>
                <td><div class="OPScore">@Html.DisplayFor(modelItem => item.Score)</div></td>
            </tr>
        }
    </table>
    <table>
        <tr>
            <td style="font-family: Arial; font-size: medium; font-weight: bold;">
                Total Operational Objectives Score:
                <input id="OPTotalScore" type="text" value="0" readonly style="border:0; outline:none;" />
            </td>
        </tr>
    </table>
}

<div style="display: none;">
    @Html.TextBox("STAG", Model.FirstOrDefault().Appraisal.Stage.ToString(), new { @class = "form-control", @readonly = "readonly" })
</div>